version: '3'

services:
  frontend:
    container_name: kickoff-frontend
    build: ./frontend
    command: npm start
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"

  backend:
    container_name: kickoff-backend
    build: ./backend
    command: python hello.py
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "5001:5000"
    depends_on:
      - frontend

  nginx:
    image: nginx:alpine
    container_name: kickoff-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend
